services:
  edge:
    container_name: embedded-pipelines-env
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    image: embedded-pipelines-env:latest

    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /home/ubuntu/.Xauthority

    volumes:
      - ./:/embedded-pipelines

      # X11 display sharing
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/ubuntu/.Xauthority:ro

      # devices
      - /dev/bus/usb:/dev/bus/usb
      
    devices:
      - /dev/dri:/dev/dri
    
    # for USB3Vision cameras
    device_cgroup_rules:
      - "c 189:* rmw"

    working_dir: /embedded-pipelines
    network_mode: host
    command: sleep infinity
