FROM ubuntu:24.04

# Required to build Ubuntu without user prompts
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Install basic libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    ca-certificates \
    curl \
    wget \
    python3-dev \
    python3-pip \
    git \
    ssh \
    libssl-dev \
    devscripts \
    build-essential \
    gdb \
    libpthread-stubs0-dev \
    vim \
    htop \
    locales \
    x11-apps \
    && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
    && locale-gen en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

# Install embedded-pipelines apt-get dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgstreamer1.0-0 \
    libgstrtspserver-1.0-dev \
    libtool \
    libxml2-dev \
    libusb-1.0-0-dev \
    cmake \
    libyaml-cpp-dev \
    freeglut3-dev \
    libmodbus-dev \
    libopencv-dev \
    doxygen \
    && rm -rf /var/lib/apt/lists/*

# Docs dependencies
RUN python3 -m pip install --break-system-packages \
    sphinx \
    breathe \
    sphinx_rtd_theme

# Change working directory to build dependencies
WORKDIR /tmp

# Install Open62541 library
RUN git clone --branch v1.5.5 https://github.com/open62541/open62541.git && \
    cd open62541 && \
    git submodule update --init --recursive && \
    mkdir build && \
    cd build && \
    cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DUA_NAMESPACE_ZERO=FULL \
    -DUA_ENABLE_METHODCALLS=ON \
    -DUA_ENABLE_NODEMANAGEMENT=ON \
    -DUA_ENABLE_NODESETLOADER=ON \
    .. && \
    make -j"$(nproc)" && \
    make install && \
    ldconfig

# Install Aravis and dependencies
RUN python3 -m pip install --break-system-packages \
    meson \
    ninja && \
    apt-get update && apt-get install -y --no-install-recommends \
    zlib1g-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module \
    gstreamer1.0-gtk3 \
    libgtk-3-dev \
    usbutils \
    ninja-build \
    udev \
    gettext \
    && rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch 0.8.36 https://github.com/AravisProject/aravis.git && \
    cd aravis && \
    meson build && \
    cd build && \
    ninja && \
    ninja install && \
    cp ../src/aravis.rules /etc/udev/rules.d/ && \
    ldconfig

RUN mkdir -p /etc/udev/rules.d && \
  tee /etc/udev/rules.d/99-imec-aravis.rules >/dev/null <<'EOF'
# IMEC
SUBSYSTEM=="usb", ATTR{idVendor}=="04b4", ATTR{idProduct}=="4d81", MODE:="0666", TAG+="uaccess", TAG+="udev-acl"
EOF

# Give sudo privileges to the existing Ubuntu 24.04 user
RUN apt-get update && apt-get install -y --no-install-recommends sudo && \
    usermod -aG sudo ubuntu && \
    echo "ubuntu ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu && \
    chmod 0440 /etc/sudoers.d/ubuntu && \
    rm -rf /var/lib/apt/lists/*

USER ubuntu

RUN mkdir -p \
    /home/ubuntu/.local/share \
    /home/ubuntu/.local/state \
    /home/ubuntu/.local/bin \
    /home/ubuntu/.config \
    /home/ubuntu/.cache \
    && chown -R ubuntu:ubuntu /home/ubuntu

WORKDIR /work
CMD ["/bin/bash"]
